---
- hosts: centos7_ssh
  user: root
  tasks:
  - file: path=/etc/ansible/facts.d state=directory owner=root group=root mode=0755 
  - copy: src=original_fact/service_enabled_systemctl.fact dest=/etc/ansible/facts.d/service_enabled.fact owner=root group=root mode=0744
